### PR TITLE
Bump gtest to May 28,2024. Move unit test lambdas out to helper functions

### LINKED ISSUE #71: Can't use upstream gtest with nvcc
Since we use lambdas in the unit tests.

Produces errors like
```
.../unit_tests/test_alltoall.cpp(46): error: The enclosing parent function ("TestBody") for an extended __host__ __device__ lambda cannot have private or protected access within its class
                     __attribute__((host)) __attribute__((device))(const int i) { sv(i) = rank + i; });
                                                                  ^

.../unit_tests/test_alltoall.cpp(53): error: The enclosing parent function ("TestBody") for an extended __host__ __device__ lambda cannot have private or protected access within its class
       __attribute__((host)) __attribute__((device))(const int &i, int &lsum) {
                                                    ^

.../unit_tests/test_alltoall.cpp(75): error: The enclosing parent function ("TestBody") for an extended __host__ __device__ lambda cannot have private or protected access within its class
                     __attribute__((host)) __attribute__((device))(const int i) { rv(i) = rank + i; });
                                                                  ^

.../unit_tests/test_alltoall.cpp(82): error: The enclosing parent function ("TestBody") for an extended __host__ __device__ lambda cannot have private or protected access within its class
       __attribute__((host)) __attribute__((device))(const int &i, int &lsum) {
```

### PR DESCRIPTION
**Pull request by cwpearson**
Google Test does support lambdas in the test body with nvcc.

Fixes https://github.com/kokkos/kokkos-comm/issues/71

### CODE REVIEW

**Review by masterleinad — DISMISSED** [review]
It's worth giving it a shot. 🙂

**Comment by cwpearson** [comment]
Sorry @masterleinad I noticed a dumb mistake

**Review by dalg24 — COMMENTED** [review]
That's a BAD idea
It means we will only be able to test against a patched googletest
Avoiding having kokkos lambdas directly in the body of the unit test and moving it to a helper function is not too bad of a constraint

**Comment by cwpearson** [comment]
Okay @dalg24 with Daniel's help I figured out what you were getting at 👍

**Review by aprokop — APPROVED** [review]
LGTM

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
